version: '2'
services:

  nginx:
    image: nginx
    container_name: nginx
    domainname: local
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.template
    volumes_from:
      - fpm
    ports:
      - "${NGINX_PORT}:80"
    environment:
      NGINX_ROOT: /var/www/html/www
      NGINX_PORT: "${NGINX_PORT}"
      NGINX_HOST: "${NGINX_HOST}"
    links:
      - fpm
    command: /bin/bash -c "envsubst '$$NGINX_ROOT $$NGINX_PORT $$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - phraseanet

  fpm:
    build: .
    container_name: fpm
    domainname: local
    volumes:
      - /var/www/html/www
    links:
      - db
      - redis
      - elasticsearch
    environment:
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      WEB_HOST: "${NGINX_HOST}"
      DB_HOST: "${DB_HOST}"
      DB_APP_NAME: "${DB_APP_NAME}"
      DB_DATA_NAME: "${DB_DATA_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    networks:
      - phraseanet

  db:
    image: mariadb
    container_name: db
    domainname: local
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      # user1:pass1@db1;user2:pass2@host2
      DATABASE_USER: "${DB_USER}"
      DATABASE_PASSWORD: "${DB_PASSWORD}"
      DATABASES: "${DB_APP_NAME},${DB_DATA_NAME}"
    volumes:
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - phraseanet

  redis:
    image: redis:alpine
    container_name: redis
    domainname: local
    networks:
      - phraseanet

  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    domainname: local
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - phraseanet

volumes:
  esdata:
    driver: local

networks:
  phraseanet:
